name: tunasync

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"
      id: go

    - name: Get dependencies
      run: |
        go get -v -t -d ./cmd/tunasync
        go get -v -t -d ./cmd/tunasynctl

    - name: Build
      run: |
        make tunasync
        make tunasynctl

    - name: Keep artifacts
      uses: actions/upload-artifact@v1
      with:
        name: tunasync-bin
        path: build-linux-amd64/
